# Файл docker-compose должен начинаться с тега версии.
# Мы используем "3" так как это - самая свежая версия на момент написания этого кода.

version: "3"



services:



  server:
 

    
    container_name: 'newApi'
    restart: 'always'

    build: ./

   

    command: npm start

  

    ports:
      - 3000:3000
      
